### ISSUE TITLE
New installation: Unknown command:"SAVE_VARIABLE"

### ISSUE THREAD

**Issue by pwlgrzs** [spooknik/FLAP#4]
Hi, I wanted to try FLAP but I am getting following problems:
1. Unknown command:"SAVE_VARIABLE"
2.  !! Error evaluating 'gcode_macro filament_unload_init:gcode': jinja2.exceptions.UndefinedError: 'extras.gcode_macro.GetStatusWrapper object' has no attribute 'save_variables' which I guess is related to above.

I am having troubles finding what could be causing this, any chance you could help?

> 12:57:33  $ FILAMENT_LOAD_INIT
> 12:57:33  // action:prompt_begin Preheat for Load
> 12:57:33  // action:prompt_text Insert filament and choose a material
> 12:57:33  // action:prompt_button_group_start
> 12:57:33  // action:prompt_button ABS - 240/100|LOAD_FILAMENT INDEX='0'
> 12:57:33  // action:prompt_button ASA - 260/105|LOAD_FILAMENT INDEX='1'
> 12:57:33  // action:prompt_button PETG - 230/85|LOAD_FILAMENT INDEX='2'
> 12:57:33  // action:prompt_button PLA - 215/60|LOAD_FILAMENT INDEX='3'
> 12:57:33  // action:prompt_button FLEX - 215/60|LOAD_FILAMENT INDEX='4'
> 12:57:33  // action:prompt_button PC - 260/105|LOAD_FILAMENT INDEX='5'
> 12:57:33  // action:prompt_button PA - 290/50|LOAD_FILAMENT INDEX='6'
> 12:57:33  // action:prompt_button_group_end
> 12:57:33  // action:prompt_show
> 12:57:36  $ LOAD_FILAMENT INDEX='0'
> 12:57:36  // action:prompt_end
> 12:57:36  echo: FLAP: ABS Selected
> 12:57:36  // Unknown command:"SAVE_VARIABLE"
> 12:57:36  // Unknown command:"SAVE_VARIABLE"
> 12:57:36  // Unknown command:"SAVE_VARIABLE"
> 12:57:36  echo: FLAP: Hotend heating!
> 12:57:39  echo: FLAP: Homing Z Axis
> 12:57:39  // action:prompt_end
> 12:57:39  echo: FLAP: Waiting for Hotend...
> 12:59:20  echo: FLAP: Filament now loading
> 12:59:33  // action:prompt_begin Loading Filament
> 12:59:33  // action:prompt_text Is the filament loaded correctly?
> 12:59:33  // action:prompt_footer_button YES|PURGE_FINISH|primary
> 12:59:33  // action:prompt_footer_button PURGE MORE|TEMP_CHECK
> 12:59:33  // action:prompt_footer_button RETRY|RETRY_LOAD_TEMP
> 12:59:33  // action:prompt_show
> 12:59:43  $ RETRY_LOAD_TEMP
> 12:59:43  // action:prompt_end
> 12:59:44  echo: FLAP: Checking if extruder is ready...
> 12:59:44  // action:prompt_end
> 12:59:44  echo: FLAP: Unloading...
> 12:59:44  !! Error evaluating 'gcode_macro filament_unload_init:gcode': jinja2.exceptions.UndefinedError: 'extras.gcode_macro.GetStatusWrapper object' has no attribute 'save_variables'
> 12:59:44  !! Error evaluating 'gcode_macro filament_unload_init:gcode': jinja2.exceptions.UndefinedError: 'extras.gcode_macro.GetStatusWrapper object' has no attribute 'save_variables'
> 12:59:44  !! Error evaluating 'gcode_macro filament_unload_init:gcode': jinja2.exceptions.UndefinedError: 'extras.gcode_macro.GetStatusWrapper object' has no attribute 'save_variables'

**Comment by spooknik** [comment]
Hello! 

Thanks for reporting this. I need to update the install wiki. 

You must add this to your printer.cfg:

```
[save_variables]
filename:~/variables.cfg
```

https://www.klipper3d.org/Config_Reference.html#save_variables

Let me know if that works.

**Comment by pwlgrzs** [comment]
Thanks, it worked. Altho I had to run a load first because empty file was throwing error:

> !! Unable to parse '' as a literal: unexpected EOF while parsing (, line 0)

After completing load cycle and getting variables file to populate with some values everything seems good to go!

**Comment by spooknik** [comment]
I'll have to look into that, it seems like it should check if it's not populated and then handle that error. Thanks for testing it out 👍
